// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

import * as React       from "react";
import * as ReasonReact from "reason-react/src/reasonReact.js";

var component = ReasonReact.statelessComponent("GreetingTwo");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", undefined, React.createElement("button", undefined, "World!"));
    });
  return newrecord;
}

export {
  component ,
  make      ,
  
}
/* component Not a pure module */
