// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

import * as Curry       from "bs-platform/lib/es6/curry.js";
import * as Json_decode from "bs-json/lib/es6/src/Json_decode.js";

function parsePost(json) {
  return /* record */[/* title */Json_decode.field("title", Json_decode.string, json)];
}

function parsePosts(json) {
  return Json_decode.array(parsePost, json);
}

function parseHackerNewsData(json) {
  return /* record */[/* hits */Json_decode.field("hits", parsePosts, json)];
}

function fetchPosts(callback) {
  fetch("/api/hacker-news").then((function (prim) {
            return prim.text();
          })).then((function (text) {
          var data = parseHackerNewsData(JSON.parse(text));
          return Promise.resolve(Curry._1(callback, data[/* hits */0]));
        }));
  return /* () */0;
}

export {
  parsePost           ,
  parsePosts          ,
  parseHackerNewsData ,
  fetchPosts          ,
  
}
/* No side effect */
