// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

import * as Home           from "./HomeContainer/Home.js";
import * as Block          from "bs-platform/lib/es6/block.js";
import * as Curry          from "bs-platform/lib/es6/curry.js";
import * as React          from "react";
import * as Greeting       from "./Greeting.js";
import * as ReasonReact    from "reason-react/lib/es6/src/reasonReact.js";
import * as HackerNewsData from "./HackerNewsData.js";

var component = ReasonReact.reducerComponent("HomeComponent");

function make() {
  var newrecord = component.slice();
  newrecord[/* didMount */4] = (function (self) {
      HackerNewsData.fetchPosts(Curry._1(self[/* reduce */3], (function (data) {
                  return /* HackerData */[data];
                })));
      return /* NoUpdate */0;
    });
  newrecord[/* render */9] = (function (param) {
      var state = param[/* state */4];
      var match = state[/* isFetching */1];
      if (match !== 0) {
        return React.createElement("h2", undefined, "loading...");
      } else {
        return React.createElement("div", undefined, ReasonReact.element(/* None */0, /* None */0, Greeting.make(/* array */[])), ReasonReact.element(/* None */0, /* None */0, Home.make(state[/* posts */0], /* array */[])));
      }
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[
              /* posts : array */[],
              /* isFetching : true */1
            ];
    });
  newrecord[/* reducer */12] = (function (action, _) {
      var posts = action[0];
      console.log(posts);
      return /* Update */Block.__(0, [/* record */[
                  /* posts */posts,
                  /* isFetching : false */0
                ]]);
    });
  return newrecord;
}

var $$default = ReasonReact.wrapReasonForJs(component, (function () {
        return make(/* array */[]);
      }));

export {
  component ,
  make      ,
  $$default ,
  $$default   as default,
  
}
/* component Not a pure module */
