// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

import * as Message     from "./Message";
import * as ReasonReact from "reason-react/lib/es6/src/reasonReact.js";

function make(name, children) {
  return ReasonReact.wrapJsForReason(Message, {
              name: name
            }, children);
}

export {
  make ,
  
}
/* ./Message Not a pure module */
