// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

import * as Pervasives from "bs-platform/lib/es6/pervasives.js";

var intEl = Pervasives.string_of_int;

function textEl(str) {
  return str;
}

export {
  intEl  ,
  textEl ,
  
}
/* No side effect */
