// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

import * as React       from "react";
import * as ReasonReact from "reason-react/lib/es6/src/reasonReact.js";

var component = ReasonReact.statelessComponent("Home");

function make(posts, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      console.log(posts);
      var postElements = posts.map((function (post) {
              return React.createElement("li", {
                          key: post.title,
                          style: {
                            fontSize: "1.5em",
                            margin: "5px 0px"
                          }
                        }, post.title);
            }));
      console.log(postElements);
      return React.createElement("div", undefined, React.createElement("ul", undefined, postElements));
    });
  return newrecord;
}

var $$default = ReasonReact.wrapReasonForJs(component, (function (jsProps) {
        return make(jsProps.posts, /* array */[]);
      }));

export {
  component ,
  make      ,
  $$default ,
  $$default   as default,
  
}
/* component Not a pure module */
