// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

import * as $$Array        from "bs-platform/lib/es6/array.js";
import * as $dot$slashHome from "./Home";
import * as ReasonReact    from "reason-react/lib/es6/src/reasonReact.js";

function make(posts, children) {
  return ReasonReact.wrapJsForReason($dot$slashHome.default, {
              posts: $$Array.map((function (post) {
                      return {
                              title: post[/* title */0]
                            };
                    }), posts)
            }, children);
}

export {
  make ,
  
}
/* ./Home Not a pure module */
