// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

import * as $$Array     from "bs-platform/lib/es6/array.js";
import * as React       from "react";
import * as ReasonReact from "reason-react/lib/es6/src/reasonReact.js";

var component = ReasonReact.statelessComponent("Home");

function make(posts, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      var postElements = $$Array.map((function (post) {
              return React.createElement("li", {
                          key: post[/* title */0],
                          style: {
                            fontSize: "1.5em",
                            margin: "5px 0px"
                          }
                        }, post[/* title */0]);
            }), posts);
      console.log(postElements);
      return React.createElement("div", undefined, React.createElement("ul", undefined, postElements));
    });
  return newrecord;
}

export {
  component ,
  make      ,
  
}
/* component Not a pure module */
